site_name: 琉璃神社
site_author: 琉璃神社
site_description: 琉璃神社是专注二次元文化的交流平台，提供动漫资源、同人创作和社群互动服务，致力于构建健康的ACGN文化生态圈。
theme:
  name: readthedocs
nav:
  - Home: index.md
  - About: about.md
  - Features: features.md
  - Contact: contact.md
